name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop
    paths:
      - 'bella-docs/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip memory]') || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
          cache-dependency-path: bella-docs/package-lock.json

      - name: Install dependencies
        run: |
          cd bella-docs
          npm ci
          
      - name: Build website
        run: |
          cd bella-docs
          npm run build

      # Popular action to deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./bella-docs/build
          # Assign commit authorship to the official GH-Actions bot
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com